[env:pimoroni_pico_plus_2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pico_plus_2w
framework = arduino
board_build.core = earlephilhower

upload_protocol = picotool
debug_tool = cmsis-dap

monitor_speed = 115200
monitor_filters = time, colorize

lib_deps = 
    adafruit/Adafruit NeoPixel@^1.15.2
    adafruit/Adafruit LSM6DS@^4.7.4
    sparkfun/SparkFun Qwiic Keypad Arduino Library@^1.0.0